illuvium/illuvium/illuvium/urls.py
from django.contrib import admin
from django.urls import include,path
from . import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('illuviumsite.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

illuvium/illuvium/illuviumsite/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'illuviumsite'

urlpatterns = [
    path('', views.activity,name='activity'),
    path('augments', views.augments,name='augments'),
    path('patchnote', views.patchnote,name='patchnote'),
    path('resources', views.resources,name='resources'),
    path('map_AbyssalBasyn', views.map_AbyssalBasyn,name='map_AbyssalBasyn'),
    path('data', views.data,name='data'),
    path('capturerate', views.capturerate,name='capturerate'),
    path('leaderboard', views.leaderboard,name='leaderboard'),
    path('google425ab4421bc49419.html/', views.google,name='google'),



]

illuvium/illuvium/login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    # path('', views.signup,name='signup'),
    path('login', views.login, name='login'),
        #ユーザの登録フォームを呼び出す
    path('create', views.showCreateUserForm, name='showCreateUserForm'),
]

illuvium/illuvium/illuviumsite/models.py
# モデル読込
from django.db import models

# コマンド
# python manage.py makemigrations illuviumsite
# python manage.py migrate              

# migrationの履歴削除
# python manage.py migrate --fake illuviumsite zero 

# tier = [("0","0"),("1","1"),("2","2"),("3","3"),("4","4"),("5","5"),]
# stage = [("1","1"),("2","2"),("3","3"),]
# モデルクラスを作成
class RateSearch(models.Model):
	# 項目定義
    IlluvialTier     = models.IntegerField(verbose_name="IlluvialTier")
    IlluvialStage    = models.IntegerField(verbose_name="IlluvialStage")
    ShardTier     = models.IntegerField(verbose_name="ShardTier")
    Captured     = models.BooleanField(verbose_name="捕獲成否")
    RegisterDate     = models.CharField(max_length=8)
    
    # テキスト表示
    def __str__(self):
    	return self.name
        

illuvium/illuvium/illuviumsite/forms.py
from django import forms
from . models import RateSearch
class RateSearchForm(forms.ModelForm):
    class Meta:
        model = RateSearch
        fields = ('IlluvialTier','IlluvialStage','ShardTier','Captured')

illuvium/illuvium/illuviumsite/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render

from .models import RateSearch
from .forms import RateSearchForm

def activity(request):

    if "user_name" in request.session:
        print("ユーザー名："+request.session["user_name"])

    context = {}
    return render(request,"illuviumsite/activity.html",context)

def augments(request):
    context = {}
    return render(request,"illuviumsite/augments.html",context)

def map_AbyssalBasyn(request):
    context = {}
    return render(request,"illuviumsite/map_AbyssalBasyn.html",context)

def leaderboard(request):
    context = {}
    return render(request,"illuviumsite/leaderboard.html",context)

def data(request):
    context = {}
    return render(request,"illuviumsite/data.html",context)


def capturerate(request):
    print('capturerate')
    context             = {}
    if request.method == 'POST':
        form = RateSearchForm(request.POST)
        print(form.is_valid())
        print(form)

        if form.is_valid():
            form.save()
    else:
        pass
        #context["userFrom"]   = RateSearch.objects.all()

        #選択肢のデータを手に入れる(都道府県文字列のリストを作る。リストの内包表記)
        #context["IlluvialTier"]  = [ p[0] for p in RateSearch.IlluvialTier.field.choices ]
        #context["IlluvialStage"]  = [ p[0] for p in RateSearch.IlluvialStage.field.choices ]
        #return render(request,"illuviumsite/capturerate.html",context)

    #context["IlluvialTier"]  = [ p[0] for p in RateSearch.IlluvialTier.field.choices ]
    #context["IlluvialStage"]  = [ p[0] for p in RateSearch.IlluvialStage.field.choices ]
    data = RateSearch.objects.all()
    t0s1s=[0,0,0,0,0,0]
    t1s1s=[0,0,0,0,0,0]
    t2s1s=[0,0,0,0,0,0]
    t3s1s=[0,0,0,0,0,0]
    t4s1s=[0,0,0,0,0,0]
    t5s1s=[0,0,0,0,0,0]

    t0s1f=[0,0,0,0,0,0]
    t1s1f=[0,0,0,0,0,0]
    t2s1f=[0,0,0,0,0,0]
    t3s1f=[0,0,0,0,0,0]
    t4s1f=[0,0,0,0,0,0]
    t5s1f=[0,0,0,0,0,0]

    for d in data:
        if d.IlluvialTier == 0:
            if d.Captured == 1:
                t0s1s[d.ShardTier] += 1
            else:
                t0s1f[d.ShardTier] += 1
        elif d.IlluvialTier == 1:
            if d.Captured == 1:
                t1s1s[d.ShardTier] += 1
            else:
                t1s1f[d.ShardTier] += 1
        elif d.IlluvialTier == 2:
            if d.Captured == 1:
                t2s1s[d.ShardTier] += 1
            else:
                t2s1f[d.ShardTier] += 1
        elif d.IlluvialTier == 3:
            if d.Captured == 1:
                t3s1s[d.ShardTier] += 1
            else:
                t3s1f[d.ShardTier] += 1
        elif d.IlluvialTier == 4:
            if d.Captured == 1:
                t4s1s[d.ShardTier] += 1
            else:
                t4s1f[d.ShardTier] += 1
        elif d.IlluvialTier == 5:
            if d.Captured == 1:
                t5s1s[d.ShardTier] += 1
            else:
                t5s1f[d.ShardTier] += 1
    print("T0S1",t0s1s,t0s1f)
    print("T1S1",t1s1s,t1s1f)
    print("T2S1",t2s1s,t2s1f)
    print("T3S1",t3s1s,t3s1f)
    print("T4S1",t4s1s,t4s1f)
    print("T5S1",t5s1s,t5s1f)

    context['ratet0s0'] = 0
    context['ratet1s1'] = 0
    context['ratet2s1'] = 0
    context['ratet2s2'] = 0
    context['ratet3s2'] = 0
    context['ratet3s3'] = 0
    context['ratet4s3'] = 0
    context['ratet4s4'] = 0
    context['ratet5s4'] = 0
    context['ratet5s5'] = 0

    try:
        context['ratet0s1'] = round(t0s1s[0]/(t0s1s[0]+t0s1f[0])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet1s1'] = round(t1s1s[1]/(t1s1s[1]+t1s1f[1])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet2s1'] = round(t2s1s[1]/(t2s1s[1]+t2s1f[1])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet2s2'] = round(t2s1s[2]/(t2s1s[2]+t2s1s[2])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet3s2'] = round(t3s1s[2]/(t3s1s[2]+t3s1f[2])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet3s3'] = round(t3s1s[3]/(t3s1s[3]+t3s1f[3])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet4s3'] = round(t4s1s[3]/(t4s1s[3]+t4s1f[3])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet4s4'] = round(t4s1s[4]/(t4s1s[4]+t4s1f[4])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet5s4'] = round(t5s1s[4]/(t5s1s[4]+t5s1f[4])*100,1)
    except Exception as e:
        print(e)
    try:
        context['ratet5s5'] = round(t5s1s[5]/(t5s1s[5]+t5s1f[5])*100,1)
    except Exception as e:
        print(e)



        
    #context["rateSearch"]   = RateSearch.objects.all()
 
    #detail.htmlへデータを渡す
    return render(request, 'illuviumsite/capturerate.html',context)



def patchnote(request):
    context = {}
    return render(request,"illuviumsite/patchnote.html",context)

def resources(request):
    context = {}
    return render(request,"illuviumsite/resources.html",context)

def google(request):
    context = {}
    return render(request,"illuviumsite/google425ab4421bc49419.html",context)

illuvium/illuvium/illuviumsite/templates/illuviumsite/activity.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<title>イルビウムの活動履歴</title>
<h2>活動履歴</h2>
<h3>Illuvium Inferno #11 PvP GUILD WARS</h3>
<pre>2024/05/04
有力ギルドから選出されたプレイヤー達で争う
日本からはpeperonti-noさんとwhityさんが参加
結果は
whityさん2回戦敗退
peperonti-noさん0回戦敗退(寝坊)
お二人ともお疲れ様でした
</pre>
<h3>Phantom Guild Ascension Tournament</h3>
<pre>日時わすれた
おそらくPB3最後のトーナメント参加人数少なめ
結果は
hisapio氏(ワイ)優勝！
whityさん3回戦くらいで敗退
強いデッキを正しく動かせば勝てるんだなと思った。当たり前
</pre>
{% endblock %}

illuvium/illuvium/illuviumsite/templates/illuviumsite/capturerate.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<title>イルビウムのオーバーワールドにおけるシャードの捕獲率</title>
<h2>シャード別捕獲率</h2>
<h3>確率表（仮）</h3>
<div>
    <span>縦列...イルビアル　横列...シャード</span><br>
    <span>※施行回数が少ないものに関しては他のTier/Stageを参考にした予想が表示されます。</span>
    
    <table class="table table-striped-columns">
        <tr>
            <td></td>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr>
            <td>Tier0</td>
            <td>{{ ratet0s1 }}%</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
        </tr>
        <tr>
            <td>Tier1</td>
            <td>不可</td>
            <td>{{ ratet1s1 }}%</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
        </tr>
        <tr>
            <td>Tier2</td>
            <td>-%</td>
            <td>{{ ratet2s1 }}%</td>
            <td>{{ ratet2s2 }}%</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
        </tr>
        <tr>
            <td>Tier3</td>
            <td>-%</td>
            <td>-%</td>
            <td>{{ ratet3s2 }}%</td>
            <td>{{ ratet3s3 }}%</td>
            <td>-%</td>
            <td>-%</td>
        </tr>
        <tr>
            <td>Tier4</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
            <td>{{ ratet4s3 }}%</td>
            <td>{{ ratet4s4 }}%</td>
            <td>-%</td>
        </tr>
        <tr>
            <td>Tier5</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
            <td>-%</td>
            <td>{{ ratet5s4 }}%</td>
            <td>{{ ratet5s5 }}%</td>
        </tr>
    </table>
    <form action="" method="post">
        {% csrf_token %}
        <span>イルビアルTier</span>
        <select name="IlluvialTier">
            <option value="0" selected>0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select><br>
        <span>イルビアルStage</span>
        <select name="IlluvialStage">
            <option value="1" selected>1</option>
            <option value="2">2</option>
            <option value="3">3</option>
        </select><br>
        <span>シャードTier</span>
        <select name="ShardTier">
            <option value="0" selected>0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select><br>
        <span>捕獲成否</span>
        <select name="Captured">
            <option value=False selected>失敗</option>
            <option value=True>成功</option>
        </select><br>
        <input type="submit" value="送信">
    </form>
</div>
{% endblock %}

illuvium/illuvium/illuviumsite/templates/illuviumsite/data copy.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<title>データ</title>
<h3>各シャードでの捕獲率
</h3>
<pre>
シャード別捕獲率
T0 t0:60%
T1
T2
</pre>
<pre>
シャード生成に必要な資源
Cured Uncommon Shard
 Uncommon Shard 1
 Hyperion 200
Cured Rare Shard
 Rare Shard 1
 Hyperion 450
Cured Epic Shard
 Epic Shard 1
 Hyperion 1000
Cured Master Shard
 Shard Dust 80
 Hyperion 6000
</pre>
<pre>
シャード破壊時に得られる資源
Cured Common Shard
Shard Dust 1
Cured Common Shard
Shard Dust 3
Cured Rare Shard
Shard Dust 7
</pre>
<br>

{% endblock %}

illuvium/illuvium/illuviumsite/templates/illuviumsite/data.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<title>データ</title>
<h3>Ingot</h3>
<img src="/media/overworld/Ingot.jpg" hight="600px" width="600px"/>

{% endblock %}

illuvium/illuvium/illuviumsite/templates/illuviumsite/google425ab4421bc49419.html
google-site-verification: google425ab4421bc49419.html

illuvium/illuvium/illuviumsite/templates/illuviumsite/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static './css/style.css' %}">
  <style>
    
  </style>
</head>
<body>
    <div class="flex" style="margin-top: 30px;margin-bottom: 50px;">
      <div><span class="maintitle"><a href="{% url 'illuviumsite:activity' %}">Illuvium Club</a></span>
      </div>
    </div>

    <div class="flex">
      <div class="left">
        <div class="navigation_title">
          <a href="{% url 'illuviumsite:activity' %}">Top</a>
        </div>
        <div class="navigation_title">
          <img src="/media/arena.png" hight="30px" width="30px"/><span class="navigation_title arena">Arena</span>
        </div>
        <!-- <div class="navigation_article" style="color:#566270;">
          ☆Arena攻略
        </div>
        <div class="navigation_article">
          <a href="{% url 'illuviumsite:leaderboard' %}">LeaderBoard</a>
        </div>
        <div class="navigation_article">
          <a href="{% url 'illuviumsite:augments' %}">Augments</a>
        </div>
        -->
        <!--

         <div class="navigation_article">
          <a href="{% url 'illuviumsite:resources' %}">OverWorldの資源</a>
        </div>
        -->
        <div class="navigation_title">
          <img src="/media/pokemon.png" hight="30px" width="30px"/><span class="navigation_title overworld">OverWorld</span>
        </div>
        <div class="navigation_article">
          <div class="navigation_article">
            <a href="{% url 'illuviumsite:map_AbyssalBasyn' %}">マップ</a>
          </div>
        </div>
        <div class="navigation_article">
          <div class="navigation_article">
            <a href="{% url 'illuviumsite:data' %}">データ</a>
          </div>
        </div>
        <!--
        <div class="navigation_article" style="color:#566270;">
          ☆シャード捕獲率
        </div>
        <div class="navigation_article" style="color:#566270;">
          ☆利益計算
        </div> -->
        <!-- <div class="navigation_title">
          <img src="/media/lisence.png" hight="30px" width="30px"/>
          <span class="navigation_title overworld">会員専用</span>
        </div> -->
        </div>


      <div class="center">
        {% block content %}
        サイトの内容
        {% endblock %}
      </div>
      <div class="right">
        <img src="/media/kurimanju.png" hight="100px" width="100px"/><br>
        管理人：hisapio<br>
        <a class="link" href="https://discord.gg/mzARYEJTW2">コミュニティはコチラ</a><br>
        まだ何もないで
      </div>
    </div>
  </body>
</html>

illuvium/illuvium/illuviumsite/templates/illuviumsite/map_AbyssalBasyn.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<title>イルビウムのオーバーワールドにおけるAbyssalBasynのマップ</title>
<h2>マップ</h2>

<h3>Brightland Steppes</h3>
<img src="/media/overworld/BrightlandSteppes.png" hight="600px" width="600px"/>
<h3>AbyssalBasyn</h3>
<img src="/media/overworld/map_AbyssalBasyn.png" hight="600px" width="600px"/>
<h3>Crymzonwaste</h3>
<img src="/media/overworld/Crymzonwaste.png" hight="600px" width="600px"/>
{% endblock %}

illuvium/illuvium/illuviumsite/templates/illuviumsite/map_crymzonwaste.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<title>イルビウムのオーバーワールドにおけるCrymzonwasteのマップ</title>
<h2>マップ</h2>
<h3>クリムゾンウェイスト
</h3>
<span style="color:yellow">●</span><span>鉱石</span><br>
<span style="color:green">●</span><span>植物</span><br>
<span style="color:blue">●</span><span>イルビアル</span><br>
<span style="color:yellow;background-color: black;">①</span><span>壁画</span><br>
<img src="/media/overworld/Crymzonwaste.png" hight="800px" width="800px"/>

<h3>壁画</h3><br>
<span>壁画②</span>
<img src="/media/overworld/picture002.png" hight="100px" width="100px"/>
<span>壁画③</span>
<img src="/media/overworld/picture003.png" hight="100px" width="100px"/>
{% endblock %}

illuvium/illuvium/illuviumsite/templates/illuviumsite/patchnote.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<title>イルビウムパッチノート</title>
<h2>パッチノート</h2>
<h3>Arena 0.2.3 Patch Notes</h3>
<h3>ゲームメカニズムの変更</h3>
<h3>エナジーゲイン</h3>
現在、ユニットがダメージを受けるとエナジーを得ることができるため、シールドを張っているタンクが強すぎる。<br>
私たちは、劇的な変更を行わずにこれを修正する方法を試しています。<br>
<h3>エネルギー獲得量の計算式を更新</h3>
シールドを張っている場合に、受けるダメージによってはエナジーを獲得できないように修正。<br>
シールドを張っている場合でも自身が攻撃したり、他の要因でのエナジー獲得は有効です。<br>
<h3>イルビアルの変更</h3>
今回の比較的小規模なパッチは、OmegaとSynergyのチューニングにより、単体対象のダメージディーラーのダメージ量を増加させることを目的としており、パフォーマンスの低いラインに焦点を当てています。<br>
リプターライン、ダッシュライン、フェルンラインといった不評のラインに焦点を当てています。<br>
<br>
<h3>リプターライン</h3>
Stage 1 — リプター<br>
Omega Damage: (8% Max Health + 100) * Omega Power → (8% Max Health + 140) * Omega Power<br>
<br>
Stage 2 — リプタラス<br>
Omega Damage: (8% Max Health + 130) * Omega Power → (8% Max Health + 170) * Omega Power<br>
<br>
Stage 3 — リプランス<br>
Omega Damage: (8% Max Health + 160) * Omega Power → (8% Max Health + 200) * Omega Power<br>
<br>
<h3>ダッシュライン</h3>
Stage 1 — Dash<br>
Omega Damage: (Attack Damage + 60) * Omega Power → (Attack Damage + 90) * Omega Power<br>
<br>
Stage 2 — Rake<br>
Omega Damage: (Attack Damage + 100) * Omega Power → (Attack Damage + 130) * Omega Power<br>
<br>
Stage 3 — Umbre<br>
Omega Damage: (Attack Damage + 150) * Omega Power → (Attack Damage + 170) * Omega Power<br>
<br>
<h3>Synergy Changes</h3>
<h4>Steam</h4>
<h5>水蒸気が発生している間における、ウォータースタック毎のエナジーリジェネ</h5>
ウォーターシナジーにつき２増加 → ウォーターシナジーにつき３増加<br>
<h4>Wildfire</h4>
<h5>ファイアシナジー毎の継続期間中のダメージ量</h5>
ファイアシナジーにつき７５ダメージ → ファイアシナジーにつき１２５ダメージ<br>
<h4>Slayer</h4>
<h5>アタックスピードバフの期間</h5>
5 seconds → 8 seconds<br>
<h4>Templar</h4>
<h5>ファイターシナジー毎のダメージ増加量</h5><br>
15% → 25%<br>
{% endblock %}

illuvium/illuvium/illuviumsite/templates/illuviumsite/top.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<h2>活動履歴</h2>
<h3>2022/12/19 Samusai Guild（ヨウさん？）主催　イルビウム国内大会に参加</h2>
国内の大会に参加しました。ルールはコンティニュー無しアリーナです。<br>
結果は<br>
    １位 whityさん<br>
    ２位 absoさん<br>
    ３位 hisapio（私）<br>
でした。みなさんおめでとうございます。
<br>

{% endblock %}