illuvium/illuvium/illuvium/urls.py
from django.contrib import admin
from django.urls import include,path
from . import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('illuviumsite.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

illuvium/illuvium/illuviumsite/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'illuviumsite'

urlpatterns = [
    path('', views.activity,name='activity'),
    path('augments', views.augments,name='augments'),
    path('patchnote', views.patchnote,name='patchnote'),
    path('resources', views.resources,name='resources'),
    path('map_AbyssalBasyn', views.map_AbyssalBasyn,name='map_AbyssalBasyn'),
    path('data', views.data,name='data'),
    path('capturerate', views.capturerate,name='capturerate'),
    path('leaderboard', views.leaderboard,name='leaderboard'),
    path('google425ab4421bc49419.html/', views.google,name='google'),



]

illuvium/illuvium/login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    # path('', views.signup,name='signup'),
    path('login', views.login, name='login'),
        #ユーザの登録フォームを呼び出す
    path('create', views.showCreateUserForm, name='showCreateUserForm'),
]

illuvium/illuvium/login/models.py
# モデル読込
from django.db import models

# コマンド
# python manage.py makemigrations login
# python manage.py migrate               
# モデルクラスを作成
class People(models.Model):
	# 項目定義
    Name     = models.CharField(max_length=50)           # 文字列
    # Mail     = models.EmailField(max_length=100)         # Email
    Password     = models.CharField(max_length=100,null=True)      # password
    
    # テキスト表示
    def __str__(self):
    	return self.name

illuvium/illuvium/login/forms.py
from django import forms
from . models import People
class UserForm(forms.ModelForm):
    class Meta:
        model = People
        fields = ('Name', 'Password')
        labels={
            'Name':'名前',
            'Password':'パスワード',
        }

illuvium/illuvium/login/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render
from . forms import UserForm
from pprint import pprint

# def signup(request):
#     context = {}
#     return render(request,"login/signup.html",context)

# 新規登録フォームHTMLへ返す
def showCreateUserForm(request):

    if request.method == 'POST':
        form = UserForm(request.POST)
        print(form.is_valid())
        print(form)

        if form.is_valid():
            form.save()
    else:
        form = UserForm()
        
    # context = {
    #     'form' : form,
    #     'AccountData': models.Account.objects.all(),
    # }
    # return render(request, 'index.html', context)


    #フォームを変数にセット
    #form = UserForm()

    context = {
        'userForm':form,
    }
 
    #detail.htmlへデータを渡す
    return render(request, 'login/signup.html',context)

# 新規登録フォームHTMLへ返す
def login(request):

    if request.method == 'POST':
        form = UserForm(request.POST)
        print(request.POST["Password"])
        print(form.is_valid())
        print(form)

        # if form.is_valid():
        #     form.save()
        #     request.session['user_name'] = request.POST["Name"]
        #     print("登録しました")
            # セッションを削除したい場合
            # del request.session['セッション名']
    else:
        form = UserForm()

    #フォームを変数にセット
    form = UserForm()

    context = {
        'userForm':form,
    }
 
    #detail.htmlへデータを渡す
    return render(request, 'login/login.html',context)

illuvium/illuvium/login/templates/login/login.html
{% extends "illuviumsite/layout.html" %}

{% block content %}
<!-- <h1>ログイン</h1> -->
 <!-- https://teratail.com/questions/134963 -->
<form action="" method="post">
    {% csrf_token %}
    <!-- {{userForm.as_p }} -->
    DISCORD名(@より後ろ):<br>
    {{ userForm.Name }}<br>
    {{ userForm.Name.errors }}<br>

    {{ userForm.Password.label_tag }}<br>
    {{ userForm.Password }}<br>
    {{ userForm.Password.errors }}<br>
    <!-- {% for error in userForm.title.errors %} -->
    <li>
        {{ error }}
    </li>
    {% endfor %}
    <!-- <button type="submit">投稿</button> -->
    <input type="submit"  class="btn btn-primary" value="ログイン">
</form>

{% endblock %}

illuvium/illuvium/login/templates/login/signup copy 2.html
 <h1>ユーザ登録</h1>
 
    <!-- <form action='{% url "showUsers" %}' method='post' class='form'>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">投稿</button>
        </form>


        
        <button type='submit' class='btn btn-outline-primary'>登録</button>
        <a href='{% url "showUsers" %}' class='btn btn-outline-secondary'>戻る</a>
    </form> -->

illuvium/illuvium/login/templates/login/signup copy 3.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<h1>ユーザ登録</h1>
 <!-- https://teratail.com/questions/134963 -->
<form action="" method="post">
    {% csrf_token %}
    <!-- {{userForm.as_p }} -->
    {{ userForm.Name.label_tag }}<br>
    {{ userForm.Name }}<br>
    {{ userForm.Name.errors }}<br>

    {{ userForm.Mail.label_tag }}<br>
    {{ userForm.Mail }}<br>
    {{ userForm.Mail.errors }}<br>
    <!-- {% for error in userForm.title.errors %} -->
    <li>
        {{ error }}
    </li>
    {% endfor %}
    <!-- <button type="submit">投稿</button> -->
    <input type="submit"  class="btn btn-primary" value="登録">
</form>

{% extends "illuviumsite/layout.html" %}

{% block content %}
<h2>活動履歴</h2>

<h3>2022/12/19 Arena 0.2.3 Patch Notesを和訳</h3>
<a href="{% url 'illuviumsite:patchnote' %}">Patchnote</a><br>
<br>
<h3>2022/12/18 Samusai Guild（ヨウさん？）主催　イルビウム国内大会に参加</h3>
・国内の大会に参加しました。ルールはコンティニュー無しアリーナです。<br>
結果は<br>
    １位 whityさん<br>
    ２位 absoさん<br>
    ３位 hisapio（私）<br>
でした。みなさんおめでとうございます。
<br>

{% endblock %}

illuvium/illuvium/login/templates/login/signup copy.html
 <h1>ユーザ登録</h1>
 
    <form action='{% url "showUsers" %}' method='post' class='form'>
        
        <button type='submit' class='btn btn-outline-primary'>登録</button>
        <a href='{% url "showUsers" %}' class='btn btn-outline-secondary'>戻る</a>
    </form>

illuvium/illuvium/login/templates/login/signup_complete.html
登録がおわりました。